services:
  captured:
    build: .
    container_name: captured-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy # Ensures MongoDB is ready before starting the app
    volumes:
      - .:/usr/src/app # Mounts project directory into the container
      - /usr/src/app/node_modules # Prevents overwriting node_modules
    env_file:
      - .env
    command: npm run dev # Ensures nodemon is running for live reload

  mongodb:
    image: mongo:8.0 # Use latest stable MongoDB version
    container_name: captured-mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - captured_mongo_data:/data/db
      - captured_mongo_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  captured_mongo_data:
  captured_mongo_config:
